version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          command: pip install --user pytest
          name: Install Pytest
      - run:
          command: ./manage.py test
          name: Check Pytest
      - run:
          command: pytest python/tests
          name: Run unit tests

