version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          command: pip install --user pytest pytest-mock requests
          name: Install Pytest
      - run:
          command: ./manage.py test
          name: Check Pytest
      - store_test_results:
           path : python/pytest-results
      - run:
          command: pytest tests
          working_directory: python
          name: Run unit tests

