# reusable steps
test_dotnet: &test_dotnet
    steps:
      - checkout
      - run:
          name : Install project dependencies
          working_directory: csharp
          command: dotnet restore
      - run:
          name : Run CSharp unit tests
          working_directory: csharp
          # XunitTests/csharp-results, JUnitTests/csharp-results, JUnitTestProject1/csharp-results
          command:
            dotnet test -v n --logger "junit;LogFilePath=csharp-results/csharp-unit-test.xml"
      - store_test_results:
           path : csharp
# -----------
# config file
# -----------
version: 2.1
orbs:
   win: cimg/windows@2.2.0
jobs:
  test_linux_typescript:
    docker:
      - image: cimg/node:10-browsers
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: npm install
          working_directory: typescript/my-app
          command: npm install
      - run:
          name: npm run test
          working_directory: typescript/my-app
          command: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - store_test_results:
          path: typescript/my-app/src/karma-results
      - run:
          name: npm run e2e
          working_directory: typescript/my-app
          command: npm run e2e -- --protractor-config=e2e/protractor.conf.js
      - store_test_results:
          path: typescript/my-app/e2e/protractor-results
  test_linux_java:
    docker:
      - image: cimg/openjdk:jdk-stretch # cimg not yet available
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

    steps: # mvn is in /opt/apache-maven/bin/mvn, current version 3.6.0
      - checkout
      - run:
          name: Install Java dependencies
          working_directory: java
          command: mvn dependency:go-offline
      - run:
          name: Run Junit tests
          working_directory: java
          command: mvn test
      - store_test_results:
          path : java/target/surefire-reports
  test_linux_python:
    docker:
      - image: cimg/python:3.8
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Install Pytest
          command: pip install --user pytest pytest-mock requests pillow
      - run:
          name: Check Pytest
          command: ./manage.py test
      - run:
          name: Run Python unit tests
          working_directory: python
          command: |
            mkdir pytest-results
            pytest tests --junitxml=pytest-results/junit.xml
      - store_test_results:
           path : python/pytest-results
      - store_artifacts:
           path : python/pytest-results
  test_linux_dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    <<: *test_dotnet
  test_windows_dotnet:
    executor:
        name: win/default
        shell: bash.exe
    <<: *test_dotnet
workflows: # run jobs sequentially
  version: 2.1
  test_all_platforms:
     jobs:
       - test_linux_typescript:
           context:
            - credentials
       - test_linux_java:
           context:
             - credentials
           requires:
             - test_linux_typescript
       - test_linux_dotnet:
           context:
             - credentials
           requires:
             - test_linux_java
       - test_windows_dotnet:
           requires:
             - test_linux_dotnet
       - test_linux_python:
           context:
             - credentials
           requires:
             - test_windows_dotnet

