# reusable steps
test_dotnet: &test_dotnet
    steps:
      - checkout
      - run:
          name : Install project dependencies
          working_directory: csharp
          command: dotnet restore
      - run:
          name : Run CSharp unit tests
          working_directory: csharp
          # XunitTests/csharp-results, JUnitTests/csharp-results, JUnitTestProject1/csharp-results
          command:
            dotnet test -v n --logger "junit;LogFilePath=csharp-results/csharp-unit-test.xml"
      - store_test_results:
           path : csharp
# -----------
# config file
# -----------
version: 2.1
orbs:
   win: circleci/windows@2.2.0
jobs:
  test_linux_python:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install Pytest
          command: pip install --user pytest pytest-mock requests
      - run:
          name: Check Pytest
          command: ./manage.py test
      - run:
          name: Run Python unit tests
          working_directory: python
          command: |
            mkdir pytest-results
            pytest tests --junitxml=pytest-results/junit.xml
      - store_test_results:
           path : python/pytest-results
      - store_artifacts:
           path : python/pytest-results
  test_linux_dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk
    <<: *test_dotnet
  test_windows_dotnet:
    executor:
        name: win/default
        shell: bash.exe
    <<: *test_dotnet
workflows: # run jobs sequentially
  version: 2.1
  test_all_platforms:
     jobs:
       - test_linux_dotnet
       - test_windows_dotnet:
            requires:
              - test_linux_dotnet
       - test_linux_python:
           requires:
             - test_windows_dotnet

